### ISSUE TITLE
react-native-plain-link, removeEventListener issue

### ISSUE THREAD

**Issue by b0n1q** [plaid/react-plaid-link#288]
Hi all!
I've got the issue with removeEventListener. Console shows the error: 

TypeError: _reactNative.Linking.removeEventListener is not a function. (In '_reactNative.Linking.removeEventListener('url', _handleListenerChange)', '_reactNative.Linking.removeEventListener' is undefined)

Posting here as react-native doesn't have issues tab

**Comment by phoenixy1** [comment]
useDeepLinkRedirector is no longer part of the sdk, so closing this issue as it should not be relevant

**Comment by hroland** [comment]
Hi @phoenixy1! We just identified widespread crashes in our app after we upgraded our SDK from 8.x.x to 10.x.x.

We couldn't find documentation of the removal of `useDeepLinkRedirector`, was this removal not documented?

Or was there a `CHANGELOG` or `@deprecated` notice that we missed? if so can you point us to it to make sure we don't miss it next time?

Cheers!

**Comment by phoenixy1** [comment]
@hroland you're right that this was not documented 😞 and the team is taking an action to improve the documentation of changes to the SDK. The PR in which the removal occurred was here: https://github.com/plaid/react-native-plaid-link-sdk/pull/521/files

If you are experiencing widespread crashes, I definitely recommend filing a support ticket or a new issue, as it's not clear (at least from the information provided here, you may have more info on your side that leads you to know that there's a relationship) if those crashes have any relationship to `useDeepLinkRedirector`.
